language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

sudo: required

install:
  - composer install --dev

services:
  - redis-server
before_install:
  - phpenv config-rm xdebug.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - ./vendor/bin/phpunit
after_script:
  - ./vendor/bin/test-reporter