home:
      pattern: /
      parameters:
        _controller: Front@Home::index
        methods:  [GET]
        routeName: home
home:
      pattern: /
      parameters:
        _controller: Front@Home::index
        methods:  [GET]
        routeName: home